#!/usr/bin/env bash
# Checks if an IP address is provided as an argument
# Pings the specified IP address 5 times

if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
